### ISSUE TITLE
alloc is required for wifi?

### ISSUE THREAD

**Issue by mart-e** [esp-rs/esp-generate#64]
Steps to reproduce:

```
$ esp-generate --chip esp32 -o wifi myproject
$ cd myproject
$ cargo check
…
   Compiling esp-hal-procmacros v0.15.0
   Compiling xtensa-lx-rt v0.17.2
error[E0463]: can't find crate for `alloc`
  --> /home/mart-e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-wifi-0.11.0/src/lib.rs:84:1
   |
84 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
The following warnings were emitted during compilation:

warning: esp-wifi@0.11.0: esp-wifi should be built with optimization level 2 or 3 - yours is s.

error: could not compile `esp-wifi` (lib) due to 1 previous error
```

Executing `esp-generate --chip esp32 -o alloc -o wifi myproject` works. I don’t know what `alloc` does but it seems it is needed when enabling `wifi`.

**Comment by bjoernQ** [comment]
Yes `alloc` (= dynamic memory allocations) is needed for WiFi and BLE - when selecting either WiFi or BLE via the TUI it will get automatically selected but apparently this doesn't work when choosing the option via command-line

Ideally no matter if selected via CLI arguments or in the TUI the behavior should be the same
